name: Build and Deploy

on:
#  push:
#    branches:
#      - main

env:
  REGISTRY_NAME: youracr.azurecr.io
  REGISTRY_USERNAME: youracr
  REGISTRY_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  AKS_RESOURCE_GROUP: your-resource-group
  AKS_CLUSTER_NAME: your-aks-cluster
  DOCKERFILE_PATH: ./path/to/Dockerfile
  IMAGE_NAME: your-image-name
  IMAGE_TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image
        run: docker build -t ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f ${{ env.DOCKERFILE_PATH }} .

      - name: Login to Azure Container Registry
        run: docker login ${{ env.REGISTRY_NAME }} -u ${{ env.REGISTRY_USERNAME }} -p ${{ env.REGISTRY_PASSWORD }}

      - name: Push Docker image to Azure Container Registry
        run: docker push ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Install Azure CLI
        uses: azure/CLI@v1

      - name: Deploy to AKS
        run: |
          az aks get-credentials --resource-group ${{ env.AKS_RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER_NAME }}
          kubectl apply -f deployment.yaml # Replace with your deployment manifest file
